name: Build Tutorial Manager Backend Image
run-name: ${{ github.actor }} is Building tutorialmanager-be image ğŸš€
on:
  workflow_dispatch: 
  push:
    paths:
    - frontend
    - backend
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      #################
      - name: Use Java 17 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.x'
      #################
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      #################
      - run: npm install -g pnpm
      - run: pushd frontend
      - run: pnpm install
      - run: pnpm install dev 
      - run: pnpm run build
      - run: popd
      - run: mvn -f backend/pom.xml -DskipTests clean package
      - run: cp -r frontend/dist backend/target/
      #################
      - name: List files in the repository
        run: |
          ls -R ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
